version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/TrelloAutotests
          name: Build
          command: |
            dotnet build TrelloAutotests.csproj

      - run:
          working_directory: ~/project/
          name: Run tests
          command: |
            dotnet test

      - store_test_results:
          path: ~/project/TrelloAutotests

workflows:
  sample: 
    jobs:
      - build-and-test
