version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project
          name: Build
          command: |
            dotnet build

      - run:
          working_directory: ~/project
          name: Run tests
          command: |
            dotnet test -v n --results-directory:test_coverage --collect:"Code Coverage"

      - store_artifacts:
          path: test/test-results.xml
      - store_artifacts:
          path: test/coverage
      - store_test_results:
          path: test

workflows:
  sample: 
    jobs:
      - build-and-test
