version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project
          name: Build
          command: |
            dotnet build

      - run:
          working_directory: ~/project
          name: Run tests
          command: |
            dotnet test --logger:xunit

      - store_test_results:
          path: ~/project/TrelloAutotests/TrelloAutotests/TestResults

workflows:
  sample: 
    jobs:
      - build-and-test
